app:
  batch-size: 100
  kafka:
    topic: mtj-msa-sp-async-transaction-ingestor



spring:
  application:
    name: mtj-msa-sp-async-transaction-ingestor
  header:
    channel: digital
    medium: web
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      "classpath:db/migration"
    sql-migration-suffixes:
      ".sql"
    sql-migration-prefix:
      V
    sql-migration-separator:
      "__"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bd_pichincha
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
 





